/** 首页底「肖类对照」静态表（对齐原站展示结构） */
export const ZODIAC_REF_ROWS: { label: string; value: string }[] = [
  { label: '俊肖', value: '鼠 牛 虎 鸡 狗 猪' },
  { label: '男肖', value: '鼠 牛 虎 龙 马 猴 狗' },
  { label: '女肖', value: '兔 蛇 羊 鸡 猪' },
  { label: '阳肖', value: '鼠 虎 龙 马 猴 狗' },
  { label: '阴肖', value: '牛 兔 蛇 羊 鸡 猪' },
  { label: '天肖', value: '牛 兔 龙 马 猴 猪' },
  { label: '地肖', value: '鼠 虎 蛇 羊 鸡 狗' },
  { label: '家肖', value: '牛 马 羊 鸡 狗 猪' },
  { label: '野肖', value: '鼠 虎 兔 龙 蛇 猴' },
  { label: '吉美', value: '兔 龙 蛇 马 羊 鸡' },
  { label: '凶丑', value: '鼠 牛 虎 猴 狗 猪' },
  { label: '单笔', value: '鼠 龙 马 蛇 鸡 猪' },
  { label: '双笔', value: '虎 猴 狗 兔 羊 牛' },
  { label: '红肖', value: '马 兔 鼠 鸡' },
  { label: '蓝肖', value: '蛇 虎 猪 猴' },
  { label: '绿肖', value: '羊 龙 牛 狗' },
  { label: '三合', value: '蛇鸡牛 虎马狗 猴鼠龙 猪兔羊' },
  { label: '六合', value: '牛羊 鼠马 龙鸡 兔狗 虎猪 蛇猴' },
  { label: '琴肖', value: '兔 蛇 鸡' },
  { label: '棋肖', value: '鼠 牛 狗' },
  { label: '书肖', value: '虎 龙 马' },
  { label: '画肖', value: '羊 猴 猪' },
  { label: '白边', value: '鼠 牛 虎 鸡 狗 猪' },
  { label: '黑中', value: '兔 龙 蛇 马 羊 猴' },
  { label: '五大', value: '牛 虎 马 猪 狗' },
  { label: '五小', value: '鼠 兔 龙 蛇 羊 鸡 猴' },
  { label: '日肖', value: '兔 马 猴 猪 牛 龙' },
  { label: '夜肖', value: '鼠 虎 蛇 羊 鸡 狗' },
]
